### PR TITLE
Add debian files.

### PR DESCRIPTION
**Pull request by likema**
You can make debian package by

```bash
dpkg-buildpackage -uc -us
```

### CODE REVIEW

**Comment by MightyCreak** [comment]
If I'm listed as the maintainer in these files, does it mean I maintain the Debian package or just the source code? (because I don't have Debian or Ubuntu on my desktop)

**Comment by MightyCreak** [comment]
The main question I have in regards to these new files is that I don't see these files on other known repositories that does have a Debian package.

Here are some repos I checked:
* https://gitlab.gnome.org/GNOME/gnome-shell
* https://gitlab.gnome.org/GNOME/gimp/
* https://github.com/obsproject/obs-studio
* https://github.com/hishamhm/htop
* https://github.com/vim/vim

I've seen this repo though that has a `debian` firectory:
* https://github.com/lutris/lutris

I wonder how the Debian packages are usually maintained when it is not included directly in the project repository, and what pros/cons there are about including them.

Understand that I am not against it, I simply want to understand :wink: 

Thank you!

**Comment by likema** [comment]
Both source code and debian package are maintained by you. However, I can help you maintain debian package if you need.

**Comment by likema** [comment]
> The main question I have in regards to these new files is that I don't see these files on other known repositories that does have a Debian package.
> 
> Here are some repos I checked and don't have a `debian` directory:
> 
> * https://gitlab.gnome.org/GNOME/gnome-shell
> * https://gitlab.gnome.org/GNOME/gimp/
> * https://github.com/obsproject/obs-studio
> * https://github.com/hishamhm/htop
> * https://github.com/vim/vim
> 
> Though I've seen this repo that does have a `debian` directory:
> 
> * https://github.com/lutris/lutris
> 
> I wonder how the Debian packages are usually maintained when it is not included directly in the project repository, and what pros/cons there are about including them.
> 
> Please understand that I am not against it, I simply want to understand 
> 
> Thank you!

Yes. Some repos include only debian files, some repos include both rpm spec and debian files, the other do not include them. It is up to the author or maintainer.

Even if repo includes debian files, it does not mean it comes into Debian/Ubuntu upstream Debian Repo, which have their own principle.

Some Debian/Ubuntu upstream projects have an independent package maintainer other than the source code author or maintainer. 

BTW, I am not a Debian/Ubuntu upstream maintainer for any open source projects.

**Comment by MightyCreak** [comment]
Since I know nothing about Debian packages, if you agree to be the maintainer of this part of repo, I would accept this PR.

Also, and to make it official, you can create a new "Package maintainers" section in the [AUTHORS](/MightyCreak/diffuse/blob/master/AUTHORS) file and, as for the translators, precise your distribution in brackets.

**Comment by joyously** [comment]
I'm interested in having the Debian package, but I think it should be in a different place, as part of a separate build process, which could create different package types. But then that's just me.
I applaud your taking this over, but I don't think you should have stuff you don't know and don't test in your repo.

**Comment by likema** [comment]
> Since I know nothing about Debian packages, if you agree to be the maintainer of this part of the repo, I would accept this PR.
> 
> Also, and to make it official, you can create a new "Package maintainers" section in the [AUTHORS](/MightyCreak/diffuse/blob/master/AUTHORS) file and, as for the translators, precise your distribution in brackets.

OK. 

Should I add myself into [AUTHORS](/MightyCreak/diffuse/blob/master/AUTHORS)  right now?

**Comment by MightyCreak** [comment]
@joyously has a good point, if I can get the time, I'd like to modularize theDiffuse code, but since I know nothing about Debian packaging, I will have to wait on you to change and test the Debian files before merging the PR. This will slow down a bit more an already very slow process.

If it is possible though, I could create a new repo just for Debian packaging purpose and give you maintainer access to it. @joyously or @likema, do you have any knowledge of how this couls be achieved?

**Comment by joyously** [comment]
I don't know much...I just arrived because I was wanting to run Diffuse on 20.04. (I got the zip of this repo and ran install.py yesterday, and it works, Hurray!)
I think if you feed this version back to the original, it could get packaged again like it was before, and be more visible. (I only searched GitHub because of a comment on SourceForge.)
My point is: how was it being done before?

**Comment by MightyCreak** [comment]
> My point is: how was it being done before?

Well, I got no idea :sweat_smile: 
Actually, I would like to package Diffuse with Flatpak (because even if I don't know how to do a Flatpak package, I do use Flatpak apps them very often, and I've heard it is not really difficult to package).

**Comment by joyously** [comment]
Since there are various ways to package things, it doesn't make sense that it's part of the source repo. Anyone can grab the source and run install.py. But packages are different for Debian and Flatpack, etc.
I'm sure you'll figure it out.

**Comment by likema** [comment]
> I don't know much...I just arrived because I was wanting to run Diffuse on 20.04. (I got the zip of this repo and ran install.py yesterday, and it works, Hurray!)
> I think if you feed this version back to the original, it could get packaged again like it was before, and be more visible. (I only searched GitHub because of a comment on SourceForge.)
> My point is: how was it being done before?

You can install diffuse on Ubuntu 20.04 from my PPA:

https://launchpad.net/~likemartinma/+archive/ubuntu/diffuse

**Comment by MightyCreak** [comment]
> I think if you feed this version back to the original, it could get packaged again like it was before, and be more visible.

I would be more than glad to do that, but I'm not sure the original owner on sourceforge is actually maintaining it any longer.

The last commit is from January 2019: https://sourceforge.net/p/diffuse/code/commit_browser

**Comment by MightyCreak** [comment]
Closing this PR, see the comments here as well as the related issue #36 to understand why.

**Pull request closed without merging**
