### PR TITLE
add new locale

### PR DESCRIPTION
**Pull request by inkhorn-ptbr**

### CODE REVIEW

**Comment by inkhorn-ptbr** [comment]
Hello dev, please revise technical aspects of this file, I only changed local language differences in translation (based on pt.po), not taking into account technical details (lack of detailed knowledge about it). I use it every day, that’s why I made this PR. Thanks

**Comment by MightyCreak** [comment]
Thanks for your contribution @inkhorn-ptbr :wink:

**Comment by inkhorn-ptbr** [comment]
you're welcome

**Comment by inkhorn-ptbr** [comment]
Hi @MightyCreak, I just updated app to the latest version 0.7.1 from flathub, and it looks like strings are not working (take a look at screenshot). It’s still on pt-pt and not pt-br. Is there something wrong with configuration or you just planning to add it later on in future?

**Comment by inkhorn-ptbr** [comment]
not_pt-br

**Comment by MightyCreak** [comment]
I'll try to find what's happening (lots of code changes recently, maybe the translations are a bit lost in space right now)

**Comment by MightyCreak** [comment]
Ok, it's fixed with PR #111 !

**Comment by inkhorn-ptbr** [comment]
great, that was fast, thank you

**Pull request merged**
