### PR TITLE
Remove lasting deprecation warnings #55

### PR DESCRIPTION
**Pull request by yuriiz**
Remove usage of deprecated Gtk.IconFactory & Gtk.ImageMenuItem

https://github.com/MightyCreak/diffuse/issues/55

### CODE REVIEW

**Comment by MightyCreak** [comment]
I like that!
Thank you for your contribution, when I have time, I'll test it locally before merging it.

**Review by MightyCreak — APPROVED** [review]
The changes looks good, need to test locally before merging.

**Comment by krlmlr** [comment]
Confirming that these changes work for me.

**Comment by MightyCreak** [comment]
I've tested locally and it doesn't work. I indeed don't have the warnings anymore, but I also lost the icons these lines were creating:

Before:  
image

After:  
image

**Comment by yuriiz** [comment]
I could not reproduce it. What distro and GTK version?
Does changing icon names to not deprecated ones fixes anything?
For example, GTK_STOCK_EXECUTE -> "system-run" as described at https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html#GTK-STOCK-EXECUTE:CAPS

**Comment by MightyCreak** [comment]
Hi @yuriiz !

I'm finally giving some love to this project ;)

To answer you questions: I'm on Fedora 34, and maybe using the non-deprecated name works, it's worth a try.

Also, here's the new link for the GTK_STOCK_EXECUTE documentation: https://docs.gtk.org/gtk3/const.STOCK_EXECUTE.html

**Comment by MightyCreak** [comment]
Since we don't have the warnings anymore (see https://github.com/MightyCreak/diffuse/issues/55#issuecomment-1127777620), I'll close this PR.

**Pull request closed without merging**
