### PR TITLE
Fix #98: Implement Rust highlighting support

### LINKED ISSUE #98: Add support for Rust syntax highlighting
Thanks for this awesome tool!

I've been mostly using Rust for the last few years professionally, so I'd love to have Rust highlighting support.

Here's the [syntax doc](https://doc.rust-lang.org/reference/keywords.html), [syntax highlighting implementation for vim](https://github.com/rust-lang/rust.vim/blob/master/syntax/rust.vim), [WIP PR](https://github.com/MightyCreak/diffuse/pull/99) and sample code:
```rust
#[derive(Clone)]
struct A<'a_bж, B> {
    x: &'a_bж B,
    z: &'static str,
}

trait Tr {}

async fn f(x: Result<(), ()>) -> Result<(), ()> {
    let _ = x?;
    Ok(())
}

async fn g() {
    f(Ok(())).await.unwrap()
}

pub fn main() -> () {
    println!("\x61\x62");
    let mut x: i32 = 1;
    let s: char = 's';
    let x: i32 = -1_322_i32;
    let x: Box<dyn Tr> = todo!();
    let zsd: usize = 123456usize;
    let фыва_1 = "asdf";
    let abra_cadabra_2 = r#"abcd"#;
    let x = 1;
    let asd = r###"sdasd sdf"###;
    let abra_cadabra_2 = r#"multiline
        string
    "#;
    let asd = r###"multiline string
        any characters '"_\/%
        abcd"###;
    return ();
}
```

### PR DESCRIPTION
**Pull request by alopatindev**

### CODE REVIEW

**Comment by MightyCreak** [comment]
Hey @alopatindev !

What's the status on your PR ?

**Comment by alopatindev** [comment]
Thanks for noticing the PR!

It works for non-exotic code. Lifetimes highlighting is not implemented yet. I hope I'll make more progress soon.

**Comment by alopatindev** [comment]
Multiline strings, macros, character literals are also unimplemented.

I'll appreciate any help. I updated https://github.com/MightyCreak/diffuse/issues/98 with source code example.

**Comment by MightyCreak** [comment]
I did a pass and added support for various comments, chars and strings syntaxes.

Since the Rust language is becoming more and more used lately, I think I'll push it as is, even if it's not feature-complete, and hope that the community will jump in to fix the different issues.

Also, it would be interesting to see if a more modern GTK widget (like the one used in GNOME Builder) could bring syntax colorization without us having to create a syntax config for each language out there.

**Pull request merged**
