### PR TITLE
Update Spanish translation

### PR DESCRIPTION
**Pull request by oscfdezdz**

### CODE REVIEW

**Comment by MightyCreak** [comment]
Also, I don't know much about Spanish, what the difference between ficheros and archivos? (In English and French, files and archives are two different things).

**Comment by oscfdezdz** [comment]
Hi, sorry I did a cleanup recently to my forked projects and I did not look at my open PRs, so it was automatically  closed with its deletion.

In Spanish, _ficheros_ and _archivos_ are sinonyms in this context. GNOME apps use _archivos_ as a translation of file. Files (Nautilus) is translated as _Archivos_, for example.

**Comment by MightyCreak** [comment]
Thanks for the answer, seems legit, I'll review your PR ASAP. I need to walk my dog for now :sweat_smile:

**Comment by MightyCreak** [comment]
Closing: superseded by #169

**Pull request closed without merging**
